name: Release Go
on:
  workflow_dispatch:
  release:
    types: [created,published] # 表示在创建新的 Release 时触发

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.36
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: go.mod # 可以指定编译使用的 Golang 版本
          binary_name: "goFile" # 可以指定二进制文件的名称
          extra_files: templates # 需要包含的额外文件
permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
